name: Deploy App

on: 
  workflow_dispatch:
    inputs:
      target_env:
        description: "Choisir l'environnement"
        required: true
        default: "INTEG"
        type: choice
        options:
          - INTEG
          - PROD
          
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.target_env }} 
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Build & Push Docker image
        run: |
          docker build -t ${{ vars.DOCKER_REGISTRY }}/${{ vars.IMAGE_NAME }}:${{ vars.IMAGE_TAG }} .
          docker push ${{ vars.DOCKER_REGISTRY }}/${{ vars.IMAGE_NAME }}:${{ vars.IMAGE_TAG }}
          
      - name: Deploy to VPS via SSH
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            echo "🚀 Déploiement sur le serveur..."
            docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}
            docker pull ${{ vars.DOCKER_REGISTRY }}/${{ vars.IMAGE_NAME }}:${{ vars.IMAGE_TAG }}
            docker stop notification-universe || true
            docker rm notification-universe || true
            docker run -d \
              --name notification-universe \
              --network nginx-proxy-manager \
              -p 5000:80 \
              -e MAILSETTINGS__URL=${{ vars.MAILSETTINGS__URL }} \
              -e MAILSETTINGS__FROM=${{ vars.MAILSETTINGS__FROM }} \
              -e MAILSETTINGS__TOKEN=${{ secrets.MAILSETTINGS__TOKEN }} \
              ${{ vars.DOCKER_REGISTRY }}/${{ vars.IMAGE_NAME }}:${{ vars.IMAGE_TAG }}
          
          
